project:
  type: website
  output-dir: docs

website:
  title: "Confeccionando Historias"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-block-border-left: "darkorange"
    code-block-bg: true
    fig-align: left



